// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $api_ai from "./routes/api/ai.ts";
import * as $api_contact from "./routes/api/contact.ts";
import * as $api_qr from "./routes/api/qr.ts";
import * as $api_sync_insights from "./routes/api/sync_insights.ts";
import * as $api_vcard from "./routes/api/vcard.ts";
import * as $contact from "./routes/contact.tsx";
import * as $ecard from "./routes/ecard.tsx";
import * as $index from "./routes/index.tsx";
import * as $insights from "./routes/insights.tsx";
import * as $partner from "./routes/partner.tsx";
import * as $programs from "./routes/programs.tsx";
import * as $services from "./routes/services.tsx";
import * as $team from "./routes/team.tsx";
import * as $AIChatAssistant from "./islands/AIChatAssistant.tsx";
import * as $ARIASummarize from "./islands/ARIASummarize.tsx";
import * as $ContactForm from "./islands/ContactForm.tsx";
import * as $HeroSlideshow from "./islands/HeroSlideshow.tsx";
import * as $Navbar from "./islands/Navbar.tsx";
import * as $ThemeToggle from "./islands/ThemeToggle.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/api/ai.ts": $api_ai,
    "./routes/api/contact.ts": $api_contact,
    "./routes/api/qr.ts": $api_qr,
    "./routes/api/sync_insights.ts": $api_sync_insights,
    "./routes/api/vcard.ts": $api_vcard,
    "./routes/contact.tsx": $contact,
    "./routes/ecard.tsx": $ecard,
    "./routes/index.tsx": $index,
    "./routes/insights.tsx": $insights,
    "./routes/partner.tsx": $partner,
    "./routes/programs.tsx": $programs,
    "./routes/services.tsx": $services,
    "./routes/team.tsx": $team,
  },
  islands: {
    "./islands/AIChatAssistant.tsx": $AIChatAssistant,
    "./islands/ARIASummarize.tsx": $ARIASummarize,
    "./islands/ContactForm.tsx": $ContactForm,
    "./islands/HeroSlideshow.tsx": $HeroSlideshow,
    "./islands/Navbar.tsx": $Navbar,
    "./islands/ThemeToggle.tsx": $ThemeToggle,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
